#!/usr/bin/env bash
# Configure Nginx redirection

# Install Nginx if not already installed
apt-get update
apt-get install -y nginx

# Configure redirection
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
