#!/usr/bin/env bash
# Install and configure Nginx to listen on port 80
apt update
apt install -y nginx
echo "server { listen 80 default_server; listen [::]:80 default_server; root /var/www/html; index index.html index.htm; server_name _; location / { try_files \$uri \$uri/ =404; } }" > /etc/nginx/sites-available/default
service nginx restart
