#!/usr/bin/env bash
# Install and configure Nginx to listen on port 80
apt update
apt install -y nginx
sed -i 's/listen \[::\]:80 default_server;/#listen \[::\]:80 default_server;/g' /etc/nginx/sites-available/default
service nginx restart
