#!/usr/bin/env bash
# This script configures the SSH client to use the private key ~/.ssh/school and refuse to authenticate using a password

cat <<EOF > ~/.ssh/config
Host *
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
EOF
